coupleNameA: Sage Isabel Nye
coupleNameB: Juan Pablo Meza
weddingDate: March 13th, 2027
weddingDateTime: '2027-03-13T21:00:00Z'
weddingLocation: San Salvador, El Salvador
colorBg: '#FFFFFF'
colorBgWhite: '#FFFFFF'
